const state={items:[],connected:false};
const $=s=>document.querySelector(s);
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]));
function cfg(){return{url:(localStorage.getItem("plexUrl")||"").replace(/\/$/,""),token:localStorage.getItem("plexToken")||""}}
function saveCfg(url,token,remember){if(remember){localStorage.setItem("plexUrl",url);localStorage.setItem("plexToken",token)}else{sessionStorage.setItem("plexUrl",url);sessionStorage.setItem("plexToken",token)}}
function getCfg(){let c=cfg();if(c.url)return c;return{url:(sessionStorage.getItem("plexUrl")||"").replace(/\/$/,""),token:sessionStorage.getItem("plexToken")||""}}
function api(path){const c=getCfg();return fetch(c.url+path+(path.includes("?")?"&":"?")+"X-Plex-Token="+encodeURIComponent(c.token),{headers:{"Accept":"application/json"}}).then(r=>{if(!r.ok)throw new Error("Plex returned "+r.status);return r.json()})}
function img(item,w=400){const c=getCfg();if(!item?.thumb||!c.url)return"";return c.url+"/photo/:/transcode?width="+w+"&height="+Math.round(w*1.5)+"&minSize=1&url="+encodeURIComponent(item.thumb)+"&X-Plex-Token="+encodeURIComponent(c.token)}
function card(item){return '<article class="card" data-key="'+esc(item.ratingKey)+'"><img class="poster" loading="lazy" src="'+esc(img(item))+'" onerror="this.style.visibility=\'hidden\'"><div class="card-title">'+esc(item.title)+'</div><p class="card-meta">'+esc(item.year||"")+(item.type==="show"?" • TV Show":" • Movie")+'</p></article>'}
function section(title,items,action){if(!items.length)return"";return '<section class="section"><div class="section-head"><h2>'+esc(title)+'</h2><button data-view="'+action+'">View all →</button></div><div class="row">'+items.slice(0,8).map(card).join("")+'</div></section>'}
function renderHome(){const movies=state.items.filter(x=>x.type==="movie"),shows=state.items.filter(x=>x.type==="show");$("#sections").innerHTML=section("Recently Added",state.items.slice().sort((a,b)=>(b.addedAt||0)-(a.addedAt||0)),"home")+section("Movies",movies,"movies")+section("TV Shows",shows,"shows");bindCards()}
function renderView(type){const items=state.items.filter(x=>type==="movies"?x.type==="movie":x.type==="show");$("#sections").innerHTML='<section class="section"><div class="section-head"><h2>'+ (type==="movies"?"Movies":"TV Shows")+'</h2></div><div class="grid">'+items.map(card).join("")+'</div></section>';bindCards()}
function bindCards(){document.querySelectorAll(".card").forEach(c=>c.onclick=()=>openItem(c.dataset.key))}
async function openItem(key){const item=state.items.find(x=>String(x.ratingKey)===String(key));if(!item)return;const c=getCfg();if(c.url){window.open(c.url+"/web/index.html#!/server/"+encodeURIComponent("local")+"/details?key="+encodeURIComponent(item.key||""),"_blank")}else alert(item.title)}
async function connect(){const c=getCfg();if(!c.url||!c.token){$("#status").textContent="Add your Plex server URL and token in Plex Settings.";return}$("#status").textContent="Connecting to Plex…";try{const data=await api("/library/sections");const dirs=data.MediaContainer?.Directory||[];state.items=[];for(const d of dirs.filter(x=>x.type==="movie"||x.type==="show")){const r=await api("/library/metadata/"+encodeURIComponent(d.key)+"/all");state.items.push(...(r.MediaContainer?.Metadata||[]).map(x=>({...x,type:x.type==="show"?"show":"movie"})))}state.connected=true;$("#status").textContent="Connected • "+state.items.length+" library items";$("#heroTitle").textContent="Welcome to your library.";$("#heroSummary").textContent="Movies and TV Shows from your Plex server.";renderHome()}catch(e){$("#status").textContent="Could not connect to Plex: "+e.message+". Check the URL, token, HTTPS/CORS, and firewall."}}
function showSettings(){const c=getCfg();$("#plexUrl").value=c.url;$("#plexToken").value=c.token;$("#settingsModal").classList.remove("hidden")}
$("#settingsBtn").onclick=showSettings;$("#searchBtn").onclick=()=>{$("#searchModal").classList.remove("hidden");$("#searchInput").focus()};$("#heroPlay").onclick=()=>{const c=getCfg();if(c.url)window.open(c.url+"/web","_blank");else showSettings()};$("#heroDetails").onclick=()=>{document.querySelectorAll(".nav").forEach(x=>x.classList.remove("active"));renderView("movies")};
$("#saveSettings").onclick=()=>{saveCfg($("#plexUrl").value.trim(),$("#plexToken").value.trim(),$("#remember").checked);$("#settingsModal").classList.add("hidden");connect()};
document.querySelectorAll("[data-close]").forEach(x=>x.onclick=()=>$("#"+x.dataset.close).classList.add("hidden"));
document.querySelectorAll(".nav").forEach(n=>n.onclick=()=>{document.querySelectorAll(".nav").forEach(x=>x.classList.remove("active"));n.classList.add("active");n.dataset.view==="home"?renderHome():renderView(n.dataset.view)});
$("#searchInput").oninput=()=>{const q=$("#searchInput").value.trim().toLowerCase();const results=state.items.filter(x=>(x.title||"").toLowerCase().includes(q)).slice(0,30);$("#searchResults").innerHTML=q?results.map(card).join(""):'<div class="empty">Start typing to search your library.</div>';bindCards()};
connect();\n// Secure proxy override — Plex credentials remain server-side.\nconst SECURE_PROXY="https://leegczvntkjniwqiphgw.supabase.co/functions/v1/plex-proxy";\nfunction secureCfg(){return{url:(localStorage.getItem("plexUrl")||"").replace(/\\/$/,""),key:localStorage.getItem("plexToken")||""}}\nfunction secureApi(path,params={}){const c=secureCfg(),q=new URLSearchParams({path,...params});return fetch(SECURE_PROXY+"?"+q,{headers:{"x-portal-key":c.key,"Accept":"application/json"}}).then(async r=>{if(!r.ok)throw Error(await r.text()||r.status);return r.json()})}\nfunction secureImg(item,w=400){if(!item?.thumb)return"";const q=new URLSearchParams({path:"/photo/:/transcode",url:item.thumb,width:w,height:Math.round(w*1.5),minSize:1});return SECURE_PROXY+"?"+q}\nasync function secureConnect(){const c=secureCfg();if(!c.key){$("#status").textContent="Open Plex Settings and enter your portal key.";return}$("#status").textContent="Connecting securely to Plex…";try{const d=await secureApi("/library/sections");state.items=[];for(const s of (d.MediaContainer?.Directory||[]).filter(x=>x.type==="movie"||x.type==="show")){const r=await secureApi("/library/metadata/"+encodeURIComponent(s.key)+"/all");state.items.push(...(r.MediaContainer?.Metadata||[]).map(x=>({...x,type:x.type==="show"?"show":"movie"})))}$("#status").textContent="Connected • "+state.items.length+" titles";$("#heroTitle").textContent="Your library. One place.";$("#heroSummary").textContent="Browse your Plex Movies and TV Shows through your private media portal.";renderHome()}catch(e){$("#status").textContent="Connection failed. Check the portal key and Supabase/Plex configuration."}}\n$("#saveSettings").onclick=()=>{localStorage.setItem("plexUrl",$("#plexUrl").value.trim().replace(/\\/$/,""));localStorage.setItem("plexToken",$("#plexToken").value.trim());$("#settingsModal").classList.add("hidden");secureConnect()};\nconnect=secureConnect;\nsecureConnect();