var passages={
mark4:{book:'Mark',ref:'4:35–41',title:'Jesus calms the storm',genre:'Gospel narrative',text:[['35','On that day, when evening had come, he said to them, “Let’s go over to the other side.”'],['36','Leaving the multitude, they took him with them, even as he was, in the boat. Other small boats were also with him.'],['37','A big wind storm arose, and the waves beat into the boat, so much that the boat was already filled.'],['38','He himself was in the stern, asleep on the cushion, and they woke him up and asked him, “Teacher, don’t you care that we are dying?”'],['39','He awoke, rebuked the wind, and said to the sea, “Peace! Be still!” The wind ceased, and there was a great calm.'],['40','He said to them, “Why are you so afraid? How is it that you have no faith?”'],['41','They were greatly afraid, and said to one another, “Who then is this, that even the wind and the sea obey him?”']]},
psalm23:{book:'Psalms',ref:'23',title:'The Lord as shepherd',genre:'Poetry / psalm',text:[['1','Yahweh is my shepherd; I shall lack nothing.'],['2','He makes me lie down in green pastures. He leads me beside still waters.'],['3','He restores my soul. He guides me in the paths of righteousness for his name’s sake.'],['4','Even though I walk through the valley of the shadow of death, I will fear no evil, for you are with me. Your rod and your staff, they comfort me.'],['5','You prepare a table before me in the presence of my enemies. You anoint my head with oil. My cup runs over.'],['6','Surely goodness and loving kindness shall follow me all the days of my life, and I will dwell in Yahweh’s house forever.']]},
phil2:{book:'Philippians',ref:'2:1–11',title:'The way of Christ',genre:'Epistle / hymn-like passage',text:[['1','If there is therefore any exhortation in Christ, any consolation of love, any fellowship of the Spirit, any tender mercies and compassion,'],['2','make my joy full by being like-minded, having the same love, being of one accord, of one mind;'],['3','doing nothing through rivalry or through conceit, but in humility, each counting others better than himself;'],['4','each of you not just looking to his own things, but each of you also to the things of others.'],['5','Have this in your mind, which was also in Christ Jesus,'],['6','who, existing in the form of God, didn’t consider equality with God a thing to be grasped,'],['7','but emptied himself, taking the form of a servant, being made in the likeness of men.'],['8','Being found in human form, he humbled himself, becoming obedient to death, yes, the death of the cross.'],['9','Therefore God also highly exalted him, and gave to him the name which is above every name,'],['10','that at the name of Jesus every knee should bow, of those in heaven, on earth, and under the earth,'],['11','and that every tongue should confess that Jesus Christ is Lord, to the glory of God the Father.']]}}
var passageArt={mark4:'https://upload.wikimedia.org/wikipedia/commons/f/f3/Rembrandt_Christ_in_the_Storm_on_the_Lake_of_Galilee.jpg',psalm23:'https://upload.wikimedia.org/wikipedia/commons/1/1f/Eastman_Johnson%2C_The_Lord_is_My_Shepherd.jpg',phil2:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Bifolio_from_Paul%27s_Letter_to_the_Romans%2C_the_end_of_Paul%27s_Letter_to_the_Philippians_and_the_beginning_of_Paul%27s_Letter_to_the_Colossians.jpg'};
var steps=[['Observe','What is actually there? Look for repeated words, contrasts, movement, characters, commands, questions, and changes.'],['Context','What surrounds the passage? Who is speaking, to whom, where does it sit in the book, and what problem or theme is developing?'],['Interpret','What is the author communicating? Separate what the text says from what you infer.'],['Connect','How does this passage fit the book, the wider biblical story, and what Scripture says elsewhere?'],['Respond','What should change in your thinking, worship, relationships, habits, or hope because of what you understood?'],['Remember','Can you explain the passage without looking? Retrieval turns study into durable knowledge.']];
var SUPABASE_URL='https://leegczvntkjniwqiphgw.supabase.co';
var SUPABASE_KEY='sb_publishable_oL48CchLp6RwHNlOUPNNkw_FXEbOWVp';
var sb=null;
function safeJSON(key,fallback){try{var v=JSON.parse(localStorage.getItem(key)||'');return v==null?fallback:v}catch(e){localStorage.removeItem(key);return fallback}}
function ensureSupabase(){if(sb)return sb;if(!window.supabase||!window.supabase.createClient){toast('Account service is still loading. Please try again.');return null}sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);return sb;}
var authMode='login',currentUser=null;
var state={view:location.hash.slice(2)||'home',step:0,current:'mark4',answers:safeJSON('selahAnswers',{}),review:safeJSON('selahReview',[])};
async function initAuth(){var client=ensureSupabase();if(!client)return;var r=await client.auth.getSession();currentUser=r.data.session?r.data.session.user:null;updateAccountUI();client.auth.onAuthStateChange(function(_e,s){currentUser=s?s.user:null;updateAccountUI();if(currentUser)syncFromCloud();});}
function updateAccountUI(){var b=document.getElementById('n-account');if(b)b.textContent=currentUser?'Account':'Sign in';}
function openAuth(){if(currentUser){accountView();return}document.getElementById('authModal').classList.remove('hidden');renderAuth();ensureSupabase();}
function closeAuth(){document.getElementById('authModal').classList.add('hidden')}
function toggleAuthMode(){authMode=authMode==='login'?'signup':'login';renderAuth()}
function renderAuth(){var signup=authMode==='signup';document.getElementById('authTitle').textContent=signup?'Create your account':'Sign in';document.getElementById('authSubmit').textContent=signup?'Create account':'Sign in';document.getElementById('authToggle').textContent=signup?'Already have an account? Sign in':'Create an account';document.getElementById('authName').classList.toggle('hidden',!signup);document.getElementById('authReset').classList.toggle('hidden',signup);document.getElementById('authMessage').textContent=signup?'Create an account to keep your Selah data synced across devices.':'Save your studies, notes and progress across devices.'}
async function submitAuth(){var client=ensureSupabase();if(!client)return;var email=document.getElementById('authEmail').value.trim(),password=document.getElementById('authPassword').value,name=document.getElementById('authName').value.trim();if(!email||!password){toast('Enter your email and password');return}var r=authMode==='signup'?await client.auth.signUp({email:email,password:password,options:{data:{display_name:name}}}):await client.auth.signInWithPassword({email:email,password:password});if(r.error){toast(r.error.message);return}closeAuth();toast(authMode==='signup'?(r.data.session?'Account created':'Check your email to confirm your account'):'Signed in');if(r.data.session)syncFromCloud()}
async function resetPassword(){var client=ensureSupabase();if(!client)return;var email=document.getElementById('authEmail').value.trim();if(!email){toast('Enter your email first');return}var r=await client.auth.resetPasswordForEmail(email,{redirectTo:location.href});toast(r.error?r.error.message:'Password reset email sent')}
async function accountView(){document.getElementById('app').innerHTML='<div class="sectionHead"><div><div class="eyebrow">Account</div><h2>Welcome back.</h2><p class="muted">'+esc(currentUser.email||'Signed in')+'</p></div><button class="btn outline" onclick="signOut()">Sign out</button></div><div class="grid"><article class="card"><h3>Cloud sync</h3><p class="muted">Your notes, studies and review data are synced to your Selah account.</p><span class="tag">Signed in</span></article><article class="card"><h3>Local data</h3><p class="muted">'+Object.keys(state.answers).length+' saved study responses on this device.</p></article></div>'}
async function signOut(){await sb.auth.signOut();toast('Signed out');route('home')}
async function syncFromCloud(){if(!currentUser)return;try{var n=await sb.from('user_notes').select('verse_id,note').eq('user_id',currentUser.id);if(!n.error){var notes=JSON.parse(localStorage.getItem('selahNotes')||'{}');n.data.forEach(function(x){notes[x.verse_id]=x.note});localStorage.setItem('selahNotes',JSON.stringify(notes))}
var s=await sb.from('review_items').select('prompt,answer,created_at').eq('user_id',currentUser.id).order('created_at',{ascending:false}).limit(20);if(!s.error){state.review=s.data.map(function(x,i){return{id:'cloud-'+i,prompt:x.prompt,answer:x.answer||'',passage:'Selah review'}});save()}toast('Synced from cloud')}catch(e){console.error(e)}}
async function cloudNote(id,n){if(!currentUser)return;var r=await sb.from('user_notes').upsert({user_id:currentUser.id,verse_id:id,note:n,updated_at:new Date().toISOString()},{onConflict:'user_id,verse_id'});if(r.error)console.error(r.error)}
async function cloudHighlight(id,on){if(!currentUser)return;var q=on?sb.from('user_highlights').upsert({user_id:currentUser.id,verse_id:id},{onConflict:'user_id,verse_id'}):sb.from('user_highlights').delete().eq('user_id',currentUser.id).eq('verse_id',id);var r=await q;if(r.error)console.error(r.error)}
async function cloudProgress(osis,chapter){if(!currentUser)return;var r=await sb.from('reading_progress').upsert({user_id:currentUser.id,book_osis:osis,chapter:chapter,updated_at:new Date().toISOString()},{onConflict:'user_id,book_osis'});if(r.error)console.error(r.error)}
async function cloudStudy(p,i,answer){
 if(!currentUser)return;
 var ref=p.book+' '+p.ref;
 var n=await sb.from('studies').upsert({user_id:currentUser.id,passage_ref:ref,title:p.title,genre:p.genre,updated_at:new Date().toISOString()},{onConflict:'user_id,passage_ref'}).select('id').single();
 if(n.error){console.error(n.error);return}
 var a=await sb.from('study_answers').upsert({study_id:n.data.id,user_id:currentUser.id,step_index:i,answer:answer,updated_at:new Date().toISOString()},{onConflict:'study_id,step_index'});
 if(a.error)console.error(a.error)
}
async function cloudReview(item,p){if(!currentUser)return;var r=await sb.from('review_items').insert({user_id:currentUser.id,study_id:null,prompt:item.prompt,answer:item.answer,next_review_at:new Date(Date.now()+86400000).toISOString()});if(r.error)console.error(r.error)}

function save(){localStorage.setItem('selahAnswers',JSON.stringify(state.answers));localStorage.setItem('selahReview',JSON.stringify(state.review))}

function toast(s){var t=document.getElementById('toast');t.textContent=s;t.classList.add('show');setTimeout(function(){t.classList.remove('show')},1800)}
function route(v){state.view=v;location.hash='/'+v;render()}
window.onhashchange=function(){state.view=location.hash.slice(2)||'home';render()}
function nav(){['home','study','library','bible','review'].forEach(function(x){var e=document.getElementById('n-'+x);if(e)e.classList.toggle('active',state.view===x)})}
function render(){nav();if(state.view==='study')study();else if(state.view==='library')library();else if(state.view==='bible')bible();else if(state.view==='review')review();else home();document.getElementById('stats').textContent=' · '+Object.keys(state.answers).length+' saved responses'}
function home(){document.getElementById('app').innerHTML='<div class="selah-home"><section class="homeHero"><div class="heroCopy reveal"><div class="heroEyebrow">A Bible learning companion</div><h1 class="heroTitle">Read deeply.<br><em>Live faithfully.</em></h1><p class="heroLead">Selah slows you down long enough to notice what Scripture actually says — then teaches you how to understand it, remember it, and live it.</p><div class="heroActions"><button class="btn" onclick="route(\'study\')">Start a guided study</button><button class="btn outline" onclick="route(\'library\')">Explore passages</button></div><div class="heroNote"><span>✦</span> Question first. Scripture first. Always.</div></div><div class="heroArt reveal"><div class="heroImageFrame"></div><img class="heroImage" src="https://upload.wikimedia.org/wikipedia/commons/f/f3/Rembrandt_Christ_in_the_Storm_on_the_Lake_of_Galilee.jpg" alt="Stylised illustration of a storm on the Sea of Galilee"><div class="heroCaption"><strong>Mark 4:35–41</strong><small>Jesus calms the storm</small></div></div><div class="scrollCue"><i></i>Scroll to explore</div></section><section class="homeSection"><div class="sectionIntro scrollReveal"><span class="sectionKicker">The Selah method</span><h2 class="sectionTitle">Slow down. Look closer.</h2><p class="sectionText">A good Bible study is not about getting to an answer as quickly as possible. It is about learning to see what is already there.</p></div><div class="methodGrid">'+steps.map(function(s,i){return '<article class="methodCard scrollReveal" data-step="'+(i+1)+'"><span class="tag">0'+(i+1)+'</span><h3>'+s[0]+'</h3><p>'+s[1]+'</p></article>'}).join('')+'</div></section><section class="homeSection"><div class="manifesto scrollReveal"><div class="manifestoMark">“</div><h2>Don’t just read the Bible.<br>Learn how to read it.</h2><p>Selah is built around a simple conviction: understanding Scripture should become a skill you carry with you, not an answer you depend on someone else to provide.</p><button class="btn" onclick="route(\'study\')">Begin your study</button></div></section></div>'}
function study(){var p=getStudyPassage(),s=steps[state.step],key=studyKey(p,state.step),val=state.answers[key]||'',art=passageArt[state.current]||'https://upload.wikimedia.org/wikipedia/commons/f/f3/Rembrandt_Christ_in_the_Storm_on_the_Lake_of_Galilee.jpg';var chips=['Repeated words','Contrasts','Questions','Commands','Character changes','Movement / setting'];var chipHtml=state.step===0?'<div class="chips">'+chips.map(function(x){return '<button class="chip" onclick="this.classList.toggle(\'selected\')">'+x+'</button>'}).join('')+'</div>':'';var html='';html+='<div class="sectionHead"><div><div class="eyebrow">Guided study</div><h2>'+esc(p.title)+'</h2><p class="muted">'+esc(p.book)+' '+esc(p.ref)+' · '+esc(p.genre)+'</p></div><div class="actions" style="margin-top:0"><button class="btn outline" onclick="backToBible()">Back to Bible</button><button class="btn outline" onclick="route(\'library\')">Choose passage</button></div></div>';html+='<div class="studyLayout"><aside class="steps">'+steps.map(function(x,i){return '<div class="step '+(i===state.step?'active':'')+'" onclick="state.step='+i+';study()"><b>'+(i+1)+'</b><span>'+x[0]+'</span></div>'}).join('')+'</aside><section><div class="passage"><div class="artPanel"><img src="'+art+'" alt="'+esc(p.title)+' illustration"><div style="padding:12px 15px"><strong>'+esc(p.title)+'</strong><div class="visualCaption">'+esc(p.book)+' '+esc(p.ref)+' · '+esc(p.genre)+' · A visual cue, not a substitute for the text.</div></div></div><div class="passageMeta"><span class="tag">'+esc(p.book)+' '+esc(p.ref)+'</span><span class="muted">'+s[0]+' · '+(state.step+1)+'/6</span></div><div class="verse">'+p.text.map(function(v){return '<span><sup>'+esc(v[0])+'</sup>'+esc(v[1])+' </span>'}).join('')+'</div><div class="coach"><strong>Your coach</strong><br>'+s[1]+'</div><div class="question"><label>'+question(state.step)+'</label>'+chipHtml+'<textarea id="answer" placeholder="'+placeholder(state.step)+'">'+esc(val)+'</textarea></div><div class="actions"><button class="btn" onclick="saveAnswer()">'+(state.step===5?'Finish study':'Save & continue')+'</button>'+(state.step>0?'<button class="btn outline" onclick="state.step--;study()">Back</button>':'')+'</div></div></section></div>';document.getElementById('app').innerHTML=html}
function getStudyPassage(){if(state.customPassage)return state.customPassage;return passages[state.current]}
function studyKey(p,i){return 'study-'+p.book+'-'+p.ref+'-'+i}
function backToBible(){if(state.customPassage){var m=state.customPassage.meta||{};bibleCurrent.book=m.book||bibleCurrent.book;bibleCurrent.chapter=m.chapter||bibleCurrent.chapter;state.customPassage=null}route('bible')}
function question(i){return ['What stands out before you explain it? Describe only things you can point to in the text.','What do you know about the scene around this passage? What should you find out before drawing conclusions?','What is the author communicating? Give your interpretation and point to the observations supporting it.','Where does this passage connect with the book’s main argument, biblical themes, or other Scripture?','What is one faithful response that follows from your interpretation — and what would be an overreach?','Close the passage. In 2–3 sentences, explain the main point and one supporting detail from memory.'][i]}
function placeholder(i){return ['Try “I notice…” rather than “I think…”.','Write what you know, then list what you would want to investigate.','Make the evidence chain visible: “I think X because I noticed Y.”','Name the connection and explain why it is relevant, not merely similar.','Be concrete. What changes? Why does the text warrant that response?','No peeking. Reconstruct the passage’s main point from memory.'][i]}
function saveAnswer(){var p=getStudyPassage(),el=document.getElementById('answer'),key=studyKey(p,state.step);state.answers[key]=el.value.trim();cloudStudy(p,state.step,state.answers[key]);if(state.step===5&&el.value.trim()){state.review.unshift({id:Date.now(),prompt:'Explain '+p.book+' '+p.ref+' in your own words.',answer:el.value.trim(),passage:p.book+' '+p.ref});state.review=state.review.slice(0,20);save();cloudReview(state.review[0],p);toast('Study saved. Review prompt created.');state.customPassage=null;route('review')}else{save();toast('Saved');if(state.step<5){state.step++;study()}}}
function library(){var b=[['Mark','Gospel narrative','mark4','4:35–41','Jesus calms the storm','https://upload.wikimedia.org/wikipedia/commons/f/f3/Rembrandt_Christ_in_the_Storm_on_the_Lake_of_Galilee.jpg'],['Psalms','Poetry / prayer','psalm23','23','The Lord as shepherd','https://upload.wikimedia.org/wikipedia/commons/1/1f/Eastman_Johnson%2C_The_Lord_is_My_Shepherd.jpg'],['Philippians','Epistle','phil2','2:1–11','The way of Christ','https://commons.wikimedia.org/wiki/Special:Redirect/file/Bifolio_from_Paul%27s_Letter_to_the_Romans%2C_the_end_of_Paul%27s_Letter_to_the_Philippians_and_the_beginning_of_Paul%27s_Letter_to_the_Colossians.jpg']];document.getElementById('app').innerHTML='<div class="sectionHead"><div><div class="eyebrow">Passage library</div><h2>Choose somewhere to slow down.</h2><p class="muted">Start small. Selah works best when you stay with a passage long enough to see its shape.</p></div></div><div class="bookGrid">'+b.map(function(x){return '<article class="book" onclick="state.current=\''+x[2]+'\';state.step=0;route(\'study\')"><img class="bookArt" src="'+x[5]+'" alt="'+x[4]+' illustration"><small>'+x[0]+' · '+x[1]+'</small><strong>'+x[4]+'</strong><span class="muted">'+x[0]+' '+x[3]+'</span></article>'}).join('')+'</div><section class="section"><div class="card"><img class="badgeMini" src="./assets/art/badge-first-study.svg" alt="First study badge"><div class="eyebrow">Visual learning</div><h3>Remember what you study.</h3><p class="muted">Selah uses simple visual anchors and badges to make important ideas easier to revisit. The image supports your memory; the text remains the source.</p><div style="clear:both"></div></div></section>'}
function review(){var item=state.review[0];document.getElementById('app').innerHTML='<div class="sectionHead"><div><div class="eyebrow">Retrieval review</div><h2>What can you still explain?</h2><p class="muted">Try to answer before revealing your saved response. Retrieval is part of learning, not just a test.</p></div><span class="tag">'+state.review.length+' prompts</span></div>'+(item?'<div class="review"><article class="card flash"><span class="tag">'+item.passage+'</span><h3>'+item.prompt+'</h3><button class="btn gold" onclick="document.getElementById(\'answerBox\').classList.remove(\'hidden\')">Reveal saved answer</button></article><article id="answerBox" class="card hidden"><h3>Your previous response</h3><div class="answer">'+esc(item.answer)+'</div><p class="muted">Compare it with what you remembered independently. What would you correct or strengthen?</p><button class="btn" onclick="state.review.shift();save();review()">I’ve reviewed it</button></article></div>':'<div class="card flash"><span class="tag">No reviews yet</span><h3>Complete a guided study and Selah will bring you back to it later.</h3><button class="btn" onclick="route(\'library\')">Start a study</button></div>')}
function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]})}

var bibleBooks=[["Gen","Genesis","OT",50],["Exod","Exodus","OT",40],["Lev","Leviticus","OT",27],["Num","Numbers","OT",36],["Deut","Deuteronomy","OT",34],["Josh","Joshua","OT",24],["Judg","Judges","OT",21],["Ruth","Ruth","OT",4],["1Sam","1 Samuel","OT",31],["2Sam","2 Samuel","OT",24],["1Kgs","1 Kings","OT",22],["2Kgs","2 Kings","OT",25],["1Chr","1 Chronicles","OT",29],["2Chr","2 Chronicles","OT",36],["Ezra","Ezra","OT",10],["Neh","Nehemiah","OT",13],["Esth","Esther","OT",10],["Job","Job","OT",42],["Ps","Psalms","OT",150],["Prov","Proverbs","OT",31],["Eccl","Ecclesiastes","OT",12],["Song","Song of Solomon","OT",8],["Isa","Isaiah","OT",66],["Jer","Jeremiah","OT",52],["Lam","Lamentations","OT",5],["Ezek","Ezekiel","OT",48],["Dan","Daniel","OT",12],["Hos","Hosea","OT",14],["Joel","Joel","OT",3],["Amos","Amos","OT",9],["Obad","Obadiah","OT",1],["Jonah","Jonah","OT",4],["Mic","Micah","OT",7],["Nah","Nahum","OT",3],["Hab","Habakkuk","OT",3],["Zeph","Zephaniah","OT",3],["Hag","Haggai","OT",2],["Zech","Zechariah","OT",14],["Mal","Malachi","OT",4],["Matt","Matthew","NT",28],["Mark","Mark","NT",16],["Luke","Luke","NT",24],["John","John","NT",21],["Acts","Acts","NT",28],["Rom","Romans","NT",16],["1Cor","1 Corinthians","NT",16],["2Cor","2 Corinthians","NT",13],["Gal","Galatians","NT",6],["Eph","Ephesians","NT",6],["Phil","Philippians","NT",4],["Col","Colossians","NT",4],["1Thess","1 Thessalonians","NT",5],["2Thess","2 Thessalonians","NT",3],["1Tim","1 Timothy","NT",6],["2Tim","2 Timothy","NT",4],["Titus","Titus","NT",3],["Phlm","Philemon","NT",1],["Heb","Hebrews","NT",13],["Jas","James","NT",5],["1Pet","1 Peter","NT",5],["2Pet","2 Peter","NT",3],["1John","1 John","NT",5],["2John","2 John","NT",1],["3John","3 John","NT",1],["Jude","Jude","NT",1],["Rev","Revelation","NT",22]];
var bibleCache={};
var bibleCurrent={book:'Gen',chapter:1};
function bibleUrl(osis){return 'https://raw.githubusercontent.com/midvash/bible-data/main/versions/en/web/books/'+osis+'.json'}

function bibleSelection(){return JSON.parse(localStorage.getItem('selahSelection')||'[]')}
function saveBibleSelection(a){localStorage.setItem('selahSelection',JSON.stringify(a))}
function toggleVerse(osis,chapter,verse){var a=bibleSelection();var id=osis+'-'+chapter+'-'+verse;var i=a.indexOf(id);if(i>=0)a.splice(i,1);else a.push(id);saveBibleSelection(a);cloudHighlight(id,i<0);loadBibleBook(osis,chapter)}
function saveVerseNote(id){var e=document.getElementById('note-'+id),n=e?e.value.trim():'';var notes=JSON.parse(localStorage.getItem('selahNotes')||'{}');if(n)notes[id]=n;else delete notes[id];localStorage.setItem('selahNotes',JSON.stringify(notes));cloudNote(id,n);toast(n?'Note saved':'Note removed')}
function studySelection(){var a=bibleSelection();if(!a.length){toast('Select at least one verse first');return}var parsed=a.map(function(id){var x=id.split('-');return{osis:x[0],chapter:Number(x[1]),verse:Number(x[2])}}).sort(function(x,y){return x.chapter-y.chapter||x.verse-y.verse});var first=parsed[0],book=bibleBooks.find(function(b){return b[0]===first.osis});if(!book){toast('Selection unavailable');return}if(parsed.some(function(x){return x.osis!==first.osis||x.chapter!==first.chapter})){toast('For now, select verses from one chapter');return}var data=bibleCache[first.osis];if(!data){toast('Open the chapter first so Selah can use its text');return}var ch=data.chapters.find(function(x){return x.chapter===first.chapter});if(!ch){toast('Chapter unavailable');return}var chosen=parsed.map(function(x){return ch.verses.find(function(v){return v.number===x.verse})}).filter(Boolean);if(!chosen.length){toast('No verses found');return}state.customPassage={book:book[1],ref:first.chapter+':'+chosen[0].number+(chosen.length>1?'–'+chosen[chosen.length-1].number:''),title:'Study '+book[1]+' '+first.chapter+':'+chosen[0].number+(chosen.length>1?'–'+chosen[chosen.length-1].number:''),genre:'Bible passage',text:chosen.map(function(v){return[String(v.number),v.text]}),meta:{book:first.osis,chapter:first.chapter}};state.step=0;route('study')}
function selectionSummary(){var a=bibleSelection();return a.length?'<div class="selectionBar"><span><span class="selectionCount">'+a.length+'</span> verse'+(a.length===1?'':'s')+' selected</span><button class="btn light" onclick="studySelection()">Study this passage</button><button class="btn outline" style="color:white;border-color:#ffffff55" onclick="saveBibleSelection([]);bible()">Clear</button></div>':''}

function bible(){
 var selected=bibleBooks.find(function(b){return b[0]===bibleCurrent.book})||bibleBooks[0];
 var side=bibleBooks.map(function(b,i){var heading=(i===0||b[2]!==bibleBooks[i-1][2])?'<div class="testament">'+(b[2]==='OT'?'Old Testament':'New Testament')+'</div>':'';return heading+'<button class="bookBtn '+(b[0]===selected[0]?'active':'')+'" onclick="openBibleBook(\''+b[0]+'\')">'+b[1]+'</button>'}).join('');
 document.getElementById('app').innerHTML='<div class="sectionHead"><div><div class="eyebrow">Bible</div><h2>The whole story, one book at a time.</h2><p class="muted">World English Bible · 66-book canon · public domain</p></div></div><div class="bibleShell"><aside class="bibleSide"><div class="biblePanel"><input id="bibleSearch" class="searchBox" placeholder="Search the whole Bible…" onkeydown="if(event.key===\'Enter\')searchBible(this.value)"><div class="bookList">'+side+'</div></div></aside><section class="bibleMain"><div id="bibleContent" class="biblePanel"><div class="loading">Loading '+selected[1]+'…</div></div></section></div>';
 loadBibleBook(selected[0],bibleCurrent.chapter);
}
async function loadBibleBook(osis,chapter){
 bibleCurrent.book=osis;bibleCurrent.chapter=chapter||1;var box=document.getElementById('bibleContent');if(!box)return;box.innerHTML='<div class="loading">Loading Scripture…</div>';
 try{if(!bibleCache[osis]){var r=await fetch(bibleUrl(osis));if(!r.ok)throw new Error('Unable to load Bible data');bibleCache[osis]=await r.json()}var b=bibleCache[osis],ch=b.chapters.find(function(x){return x.chapter===bibleCurrent.chapter})||b.chapters[0];bibleCurrent.chapter=ch.chapter;cloudProgress(osis,ch.chapter);
 var buttons=b.chapters.map(function(x){return '<button class="chapterBtn '+(x.chapter===ch.chapter?'active':'')+'" onclick="loadBibleBook(\''+osis+'\','+x.chapter+')">'+x.chapter+'</button>'}).join('');
 var selected=bibleSelection(),notes=JSON.parse(localStorage.getItem('selahNotes')||'{}');
 box.innerHTML='<div class="readerHead"><div><div class="eyebrow">'+b.testament+' · '+b.englishName+'</div><h1>'+b.englishName+' '+ch.chapter+'</h1><p class="muted">World English Bible</p></div><button class="btn outline" onclick="copyBibleRef(\''+osis+'\','+ch.chapter+')">Copy reference</button></div><p class="selectionHint">Click a verse to select it. Select verses you want to study together.</p><div class="chapterNav">'+buttons+'</div><div class="readerText">'+ch.verses.map(function(v){var id=osis+'-'+ch.chapter+'-'+v.number,sel=selected.indexOf(id)>=0?' selected':'',note=notes[id]?' note':'';return '<span class="readerVerse'+sel+note+'" id="'+id+'" onclick="toggleVerse(\''+osis+'\','+ch.chapter+','+v.number+')" title="Select verse"><sup>'+v.number+'</sup>'+esc(v.text)+'</span>'}).join('')+'</div><div class="verseTools"><button class="miniBtn" onclick="toggleContext()">Show context guide</button><button class="miniBtn" onclick="showNotes()">Notes for this chapter</button></div><div id="contextGuide" class="studyPrompt hidden"><h3>Before you interpret</h3><p>Ask what comes immediately before and after this chapter, who is speaking, what kind of writing you are reading, and what the author is doing in the surrounding section.</p><div class="contextGrid"><div class="contextCard"><strong>Observe</strong>What repeats, changes, contrasts, or surprises you?</div><div class="contextCard"><strong>Context</strong>What problem, audience, setting, or argument surrounds it?</div><div class="contextCard"><strong>Evidence</strong>What can you point to in the text before making an inference?</div></div></div><div id="notesPanel" class="noteBox hidden"><h3>Chapter notes</h3>'+ch.verses.map(function(v){var id=osis+'-'+ch.chapter+'-'+v.number;return '<div style="margin:10px 0"><label class="muted">'+v.number+'</label><textarea id="note-'+id+'" placeholder="Your note…">'+esc(notes[id]||'')+'</textarea><button class="miniBtn" onclick="saveVerseNote(\''+id+'\')">Save note</button></div>'}).join('')+'</div>'+selectionSummary();
 window.scrollTo({top:0,behavior:'smooth'});
 }catch(e){box.innerHTML='<div class="card"><h3>Could not load this book</h3><p class="muted">'+esc(e.message)+'</p><button class="btn" onclick="bible()">Try again</button></div>'}
}
function toggleContext(){var e=document.getElementById('contextGuide');if(e)e.classList.toggle('hidden')}
function showNotes(){var e=document.getElementById('notesPanel');if(e)e.classList.toggle('hidden')}

function copyBibleRef(osis,chapter){var b=bibleBooks.find(function(x){return x[0]===osis});var text=b[1]+' '+chapter;if(navigator.clipboard)navigator.clipboard.writeText(text);toast(text+' copied')}
function openBibleBook(osis){bibleCurrent.book=osis;bibleCurrent.chapter=1;bible()}
async function searchBible(query){
 query=query.trim().toLowerCase();if(!query){toast('Enter a word or phrase to search');return}
 var box=document.getElementById('bibleContent');box.innerHTML='<div class="loading">Searching all 66 books…</div>';
 try{var results=[];await Promise.all(bibleBooks.map(async function(b){if(!bibleCache[b[0]]){var r=await fetch(bibleUrl(b[0]));if(!r.ok)throw new Error('Search data unavailable');bibleCache[b[0]]=await r.json()}var data=bibleCache[b[0]];data.chapters.forEach(function(ch){ch.verses.forEach(function(v){if(v.text.toLowerCase().includes(query)&&results.length<200)results.push({osis:b[0],book:b[1],chapter:ch.chapter,verse:v.number,text:v.text})})})}));results.sort(function(a,b){return a.book.localeCompare(b.book)||a.chapter-b.chapter||a.verse-b.verse});box.innerHTML='<div class="readerHead"><div><div class="eyebrow">Bible search</div><h2>'+results.length+(results.length===200?'+':'')+' results</h2><p class="muted">Searching the full 66-book WEB dataset.</p></div><button class="btn outline" onclick="bible()">Back to books</button></div><div class="searchResults">'+(results.length?results.map(function(x){return '<article class="result" onclick="openBibleResult(\''+x.osis+'\','+x.chapter+','+x.verse+')"><div class="resultRef">'+x.book+' '+x.chapter+':'+x.verse+'</div><div class="resultText">'+esc(x.text)+'</div></article>'}).join(''):'<div class="card"><h3>No matches</h3><p class="muted">Try a different word or phrase.</p></div>')+'</div>'}
 catch(e){box.innerHTML='<div class="card"><h3>Search failed</h3><p class="muted">'+esc(e.message)+'</p></div>'}
}
function openBibleResult(osis,chapter,verse){bibleCurrent.book=osis;bibleCurrent.chapter=chapter;bible();setTimeout(function(){var el=document.getElementById(osis+'-'+chapter+'-'+verse);if(el){el.scrollIntoView({behavior:'smooth',block:'center'});el.style.background='#efeadd';setTimeout(function(){el.style.background=''},1800)}},500)}

function bootSelah(){window.selahBooted=true;try{if(typeof render!=='function')throw new Error('Selah app script did not load correctly');render();setTimeout(initAuth,0)}catch(e){console.error('Selah boot error:',e);var app=document.getElementById('app');if(app)app.innerHTML='<div class="card"><h2>Selah could not start</h2><p class="muted">The app JavaScript failed to start. Open the browser console for the exact error.</p><button class="btn" onclick="location.reload()">Reload Selah</button></div>'}}if(document.readyState==='loading'){document.addEventListener('DOMContentLoaded',bootSelah)}else{bootSelah()}